### ISSUE TITLE
Patch: std_match for SLV

### ISSUE THREAD

**Issue by donnie-j** [ghdl/ghdl#1121]
Here is a patch that adds support for std_match on std_logic_vector types, just a copy of std_ulogic_vector.

```
diff --git a/src/synth/synth-oper.adb b/src/synth/synth-oper.adb
index 513eef62..41495a23 100644
--- a/src/synth/synth-oper.adb
+++ b/src/synth/synth-oper.adb
@@ -1433,6 +1433,21 @@ package body Synth.Oper is
             begin
                return Synth_Shift_Rotate (Id_Ror, L, R, Expr);
             end;
+         when Iir_Predefined_Ieee_Numeric_Std_Match_Slv =>
+            declare
+               L : constant Value_Acc := Get_Value (Subprg_Inst, Param1);
+               R : constant Value_Acc := Get_Value (Subprg_Inst, Param2);
+            begin
+               if Is_Static (L) then
+                  return Synth_Std_Match (L, R, Expr);
+               elsif Is_Static (R) then
+                  return Synth_Std_Match (R, L, Expr);
+               else
+                  Error_Msg_Synth
+                    (+Expr, "one operand of std_match must be constant");
+                  return null;
+               end if;
+            end;
          when Iir_Predefined_Ieee_Numeric_Std_Match_Suv =>
             declare
                L : constant Value_Acc := Get_Value (Subprg_Inst, Param1);
```

**Comment by eine** [comment]
Hi @donnie-j, since you already have a GitHub account, I'd suggest to submit patches as Pull Requests (PRs), instead of submitting them as code blocks in plain issues. This is because PRs will trigger the Continuous Integration (CI) workflows to build and test the modifications. Moreover, if the feature you are trying to fix is not covered by test yet, adding it is desirable.

Note that none of this is really required for this specific and small patch. However, if you are not familiar with the collaboration procedure based on PRs, it can be a good case to learn. Should you need any help/guidelines, please let us know.
