### ISSUE TITLE
GHDL logo in README.md is poorly visible in dark mode

### ISSUE THREAD

**Issue by avinal** [ghdl/ghdl#1546]
Since GitHub rolled out dark theme a few days ago, more and more users are shifting to it. The **GHDL** logo is barely visible in this mode. (See below). However, this doesn't affect the project in any way but important for professional and aesthetic purposes.
![image](https://user-images.githubusercontent.com/74113200/102972597-50658580-4521-11eb-8aa7-81367c5a5408.png)

Possible fix: Add an outline to the logo or change the color to gray

**Comment by tgingold** [comment]
a PR is always welcome!

**Comment by avinal** [comment]
> 
> 
> a PR is always welcome!

I would like to know the preference before pr, I have following suggestions:
- Change color to gray (or whatever you suggest)
- Add an outline to text (white outline)
- Add a white/textured background to the logo

**Comment by eine** [comment]
A proposal: https://github.com/eine/ghdl/blob/logo/README.md

![banner](https://user-images.githubusercontent.com/6628437/103434277-63521700-4bff-11eb-8596-51629153ab24.png)

The concept: the logo is defined as four 7x5 pixel characters, spaced by one pixel. The following script generates an SVG to be used as a reference: https://github.com/eine/ghdl/blob/logo/logo/gen_logo.py.

Pixels can optionally have an outline. In these examples, there is a transparent outline (10%). Behind the pixels, there is a gaussian blur. The background is white noise behind a black layer with 95% opacity. There is a frame with a gradient.

See an square version below, which might be used for the organisation and as a favicon:

![icon](https://user-images.githubusercontent.com/6628437/103434276-60572680-4bff-11eb-8e92-5cdee22d06f7.png)

![org_dark](https://user-images.githubusercontent.com/6628437/103434291-8e3c6b00-4bff-11eb-8011-eb543a55d67f.png)

![org_light](https://user-images.githubusercontent.com/6628437/103434293-9399b580-4bff-11eb-9217-b6972a3f0743.png)

Using green "LEDs" instead of blue:

![banner_green](https://user-images.githubusercontent.com/6628437/103434278-6e0cac00-4bff-11eb-86f7-3e2fcca51110.png)

![icon_green](https://user-images.githubusercontent.com/6628437/103434279-6fd66f80-4bff-11eb-9f33-dfdc46a1cdd0.png)

**Comment by tgingold** [comment]
Up to you!

**Comment by tgingold** [comment]
I'm fine with the blue logo.

**Comment by eine** [comment]
I updated the README, the docs and the favicon of the docs with the blue logo proposed above. I removed the black background, since it didn't feel necessary with the blue version.

@tgingold, I cannot change the icon of the organisation in GitHub. Can you please use https://github.com/ghdl/ghdl/blob/master/logo/icon.png ?
