### ISSUE TITLE
Release asset names

### ISSUE THREAD

**Issue by Paebbels** [ghdl/ghdl#2375]
Can we rename some release assets to have a cleaner naming scheme?

![image](https://user-images.githubusercontent.com/956109/223053897-681de5d1-6071-4374-b5e0-87114976f272.png)

* `ghdl-gha-ubuntu...` &rarr; `ghdl-ubuntu...`
* `ghdl-MINGW32.zip` &rarr; `ghdl-mingw32.zip`
* `ghdl-UCRT64.zip` &rarr; `ghdl-ucrt64.zip`

**Questions:**
* What's `ghdl.1` for?
* Where are the standalones?

**Comment by umarcor** [comment]
They can be changed, but https://github.com/ghdl/setup-ghdl-ci needs to be updated accordingly, because it consumes those asset names from release nightly. Not the standalones, but the ones for Ubuntu.

I believe that the standalone are the zipfiles. The gz tarballs are for linux and the zst ones are for MSYS2. However, that was changed in the past weeks and I did not review the details.

ghdl.1 is the man page generated by sphinx.
